# Generated by Django 4.0.3 on 2022-05-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bac17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bac17username', models.CharField(max_length=500, verbose_name='Identifiant')),
                ('bac17mdp', models.CharField(max_length=500, verbose_name='numéro transaction')),
                ('bac17refresh', models.CharField(max_length=500, verbose_name='Info API')),
            ],
        ),
    ]
