# Generated by Django 4.0.3 on 2022-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bac17'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg002',
            name='pg002numeroz',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110auth',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Auth'),
        ),
    ]
