# Generated by Django 4.0.3 on 2022-05-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pg002_pg002numeroz_alter_ps110_ps110auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg002',
            name='pg002numeroz',
        ),
    ]
