# Generated by Django 4.0.3 on 2022-05-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pg101_ps003code_remove_ps003_pg001_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ps003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps003id', models.CharField(max_length=500, unique=True)),
                ('ps003numero_compte', models.IntegerField(unique=True, verbose_name='Numéro de compte')),
                ('ps003morant', models.FloatField(default=0, verbose_name='Morant')),
                ('ps003estbloque', models.BooleanField(default=False, verbose_name='Bloquer le compte')),
                ('ps003compte_groupe', models.BooleanField(default=False, verbose_name='Valide ou pas')),
                ('statut_valide', models.BooleanField(default=True, verbose_name='Valide ou pas')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateModification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('pg001_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.pg001', verbose_name='Groupe')),
                ('pg002_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.pg002', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Compte',
                'ordering': ['ps003numero_compte'],
            },
        ),
        migrations.CreateModel(
            name='Pg101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg101id', models.CharField(max_length=500, verbose_name='Identifiant')),
                ('pg101numTransaction', models.CharField(max_length=500, verbose_name='numéro transaction')),
                ('pg101somme_initial', models.FloatField(verbose_name='somme')),
                ('pg101somme', models.FloatField(verbose_name='somme')),
                ('pg101frais', models.FloatField(verbose_name='frais_api')),
                ('pg101info_api', models.CharField(blank=True, max_length=500, null=True, verbose_name='Info API')),
                ('pg101info_api2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Info API 2')),
                ('pg101info_api3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Info API 3')),
                ('pg101state', models.BooleanField(verbose_name='Etat de la recharge')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateModification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ps003code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.ps003', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Historique des rechargements',
                'ordering': ['pg101id'],
            },
        ),
        migrations.CreateModel(
            name='Pg100',
            fields=[
                ('pg100id', models.AutoField(primary_key=True, serialize=False)),
                ('pg101numTransaction', models.CharField(max_length=500, unique=True, verbose_name='numéro transaction')),
                ('pg100somme_initial', models.FloatField(max_length=500, verbose_name='somme initial')),
                ('pg100somme', models.FloatField(max_length=500, verbose_name='solde_envoye')),
                ('pg100state', models.BooleanField(default=True, verbose_name='Etat')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateModification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('pg105_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Envoi', to='api.pg105', verbose_name='Frais')),
                ('ps003codeEnvoi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Envoi', to='api.ps003', verbose_name='Compte envoi')),
                ('ps003codeRecu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Recu', to='api.ps003', verbose_name='Compte reçu')),
            ],
            options={
                'verbose_name': 'Historique de rechargement',
                'ordering': ['pg100id'],
            },
        ),
    ]
