# Generated by Django 4.0.3 on 2022-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ps003_pg101_pg100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg002',
            name='pg002compte_valide',
            field=models.BooleanField(default=False, verbose_name='Test'),
        ),
    ]
