# Generated by Django 4.0.3 on 2022-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pg002_pg002compte_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg002',
            name='pg002essai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps expiration'),
        ),
        migrations.AlterField(
            model_name='bac17',
            name='bac17mdp',
            field=models.CharField(max_length=255, verbose_name='numéro transaction'),
        ),
        migrations.AlterField(
            model_name='bac17',
            name='bac17refresh',
            field=models.CharField(max_length=255, verbose_name='Info API'),
        ),
        migrations.AlterField(
            model_name='bac17',
            name='bac17username',
            field=models.CharField(max_length=255, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001numeroEntreprise',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero entreprise'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001numeroRegistreCommerce',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero registre commerce'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001raisonSocial',
            field=models.CharField(max_length=200, verbose_name='Nom du groupe'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001siegeSocial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Siège social'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001sigle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SIGLE'),
        ),
        migrations.AlterField(
            model_name='pg001',
            name='pg001siteWeb',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002auth',
            field=models.TextField(blank=True, null=True, verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002numeroidentification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro identification'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002otp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code OTP'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002qrcode',
            field=models.TextField(blank=True, null=True, verbose_name='Qr code'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002sexe',
            field=models.CharField(choices=[('M', 'MASCULIN'), ('F', 'FEMININ')], max_length=200, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='pg002',
            name='pg002typiece',
            field=models.CharField(blank=True, choices=[('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT'), ('PDC', 'PERMIS DE CONDUIRE'), ('AUTRES', 'AUTRES')], max_length=200, null=True, verbose_name='Numéro identification'),
        ),
        migrations.AlterField(
            model_name='pg003',
            name='pg003id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pg100',
            name='pg100somme',
            field=models.FloatField(max_length=200, verbose_name='solde_envoye'),
        ),
        migrations.AlterField(
            model_name='pg100',
            name='pg100somme_initial',
            field=models.FloatField(max_length=200, verbose_name='somme initial'),
        ),
        migrations.AlterField(
            model_name='pg100',
            name='pg101numTransaction',
            field=models.CharField(max_length=200, unique=True, verbose_name='numéro transaction'),
        ),
        migrations.AlterField(
            model_name='pg101',
            name='pg101id',
            field=models.CharField(max_length=200, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='pg101',
            name='pg101info_api',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Info API'),
        ),
        migrations.AlterField(
            model_name='pg101',
            name='pg101info_api2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Info API 2'),
        ),
        migrations.AlterField(
            model_name='pg101',
            name='pg101info_api3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Info API 3'),
        ),
        migrations.AlterField(
            model_name='pg101',
            name='pg101numTransaction',
            field=models.CharField(max_length=200, verbose_name='numéro transaction'),
        ),
        migrations.AlterField(
            model_name='pg103',
            name='pg103libele',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pg104',
            name='pg104libele',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ps003',
            name='ps003id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110auth',
            field=models.TextField(blank=True, null=True, verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110code',
            field=models.TextField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110imei',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Imei'),
        ),
        migrations.AlterField(
            model_name='ps110',
            name='ps110telephone',
            field=models.CharField(max_length=200, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='ps111',
            name='ps111auth',
            field=models.TextField(blank=True, null=True, verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='ps111',
            name='ps111code',
            field=models.TextField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ps111',
            name='ps111id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ps111',
            name='ps111imei',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Imei'),
        ),
        migrations.AlterField(
            model_name='ps111',
            name='ps111telephone',
            field=models.CharField(max_length=200, verbose_name='Marque'),
        ),
    ]
