# Generated by Django 4.0.3 on 2022-05-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pg002_pg002essai_alter_bac17_bac17mdp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg002',
            name='pg002compte_valide',
        ),
    ]
