# Generated by Django 4.0.3 on 2022-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pg002_pg002compte_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg002',
            name='pg002timeessai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps essaie'),
        ),
    ]
