# Generated by Django 4.0.3 on 2022-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pg002_pg002essai_alter_pg002_pg002timeessai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg002',
            name='pg002essai',
        ),
        migrations.RemoveField(
            model_name='pg002',
            name='pg002timeessai',
        ),
    ]
