# Generated by Django 4.0.3 on 2022-05-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_pg002_pg002essai_remove_pg002_pg002timeessai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ps110',
            name='ps110code',
        ),
        migrations.RemoveField(
            model_name='ps110',
            name='ps110imei',
        ),
        migrations.RemoveField(
            model_name='ps110',
            name='ps110statut_enregistre',
        ),
        migrations.RemoveField(
            model_name='ps110',
            name='ps110statut_valide',
        ),
    ]
