# Generated by Django 4.0.3 on 2022-05-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_pg100_pg105_id_pg100_ps003frais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps003',
            name='ps003compte_cinit',
            field=models.BooleanField(default=True),
        ),
    ]
