# Generated by Django 4.0.3 on 2022-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ps003_ps003compte_cinit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pg100',
            old_name='ps003frais',
            new_name='pg100frais',
        ),
        migrations.AddField(
            model_name='ps003',
            name='ps003plafond',
            field=models.IntegerField(default=0, verbose_name='Plafond'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ps003',
            name='ps003timesomme',
            field=models.FloatField(default=0, verbose_name='Plafond'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ps003',
            name='ps003timetransaction',
            field=models.IntegerField(default=0, verbose_name='Plafond'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ps003',
            name='ps003compte_cinit',
            field=models.BooleanField(default=False),
        ),
    ]
