# Generated by Django 4.0.3 on 2022-05-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_ps003frais_pg100_pg100frais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme_initiale', models.FloatField(verbose_name='Somme Initiale')),
                ('somme', models.FloatField(verbose_name='Somme')),
                ('frais', models.FloatField(verbose_name='Frais')),
                ('caisse', models.FloatField(verbose_name='Caisse')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateModification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
        ),
        migrations.AlterField(
            model_name='ps003',
            name='ps003numero_compte',
            field=models.BigIntegerField(unique=True, verbose_name='Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='ps003',
            name='ps003timetransaction',
            field=models.BigIntegerField(verbose_name='Plafond'),
        ),
    ]
