# Generated by Django 4.0.3 on 2022-05-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pg002_pg002ps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg001',
            name='pg103_id',
        ),
        migrations.RemoveField(
            model_name='pg001',
            name='pg104_id',
        ),
    ]
