# Generated by Django 4.0.3 on 2022-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_pg003_pg003mdp_alter_pg003_pg003plafond'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg003',
            name='pg003otp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code OTP'),
        ),
        migrations.AddField(
            model_name='pg003',
            name='pg003otp_expired',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps expiration'),
        ),
        migrations.AlterField(
            model_name='pg003',
            name='pg003mdp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mot de passe'),
        ),
    ]
