# Generated by Django 4.0.3 on 2022-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pg003_pg003otp_pg003_pg003otp_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg001',
            name='pg001identifiant',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
