# Generated by Django 4.0.3 on 2022-05-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_pg003_pg003estbloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ps111',
            name='pg002_id',
        ),
        migrations.RemoveField(
            model_name='ps111',
            name='ps111code',
        ),
        migrations.RemoveField(
            model_name='ps111',
            name='ps111imei',
        ),
        migrations.RemoveField(
            model_name='ps111',
            name='ps111statut_enregistre',
        ),
        migrations.RemoveField(
            model_name='ps111',
            name='ps111statut_valide',
        ),
    ]
