# Generated by Django 4.0.3 on 2022-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pg001_pg001telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg001',
            name='pg001otp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code OTP'),
        ),
        migrations.AddField(
            model_name='pg001',
            name='pg001otp_expired',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps expiration'),
        ),
    ]
